name: Dependencies Installation
description: Install dependencies

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        npm ci
        composer install --optimize-autoloader --prefer-dist
        composer install --no-scripts --no-dev
        composer dump-autoload
