name: Automated Latest Release

on:
  workflow_dispatch:
    inputs:
      channel:
        required: true
        type: choice
        description: Select a channel. For cloud, use main branch only!
        options:
          - ga
          - beta
          - cloud
      PRERELEASE:
        type: boolean
        description: 'Pre-release?'
        required: false

env:
  CHANNEL: ${{inputs.channel}}
  PRERELEASE: 'false'

permissions:
  contents: write
  id-token: write
  pull-requests: write

# Cancel in-progress jobs or runs for the current workflow run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  latest_release:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Set POSTFIX value
        id: set_postfix_value
        uses: ./.github/workflows/set-postfix-value
        with:
          PRERELEASE: ${{ env.PRERELEASE }}

      - name: Env Vars Configure
        id: env_vars_configure
        uses: ./.github/workflows/env-vars-configure
        with:
          CHANNEL: ${{ env.CHANNEL }}
          REF: ${{ github.ref }}
          POSTFIX: ${{ steps.set_postfix_value.outputs.postfix }}

      - name: Install Dependencies
        uses: ./.github/workflows/install-dependencies
      - name: Build plugin
        uses: ./.github/workflows/build-plugin
        with:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          BUILD_SCRIPT_PATH: "./.github/scripts/build-zip.sh"
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          target_commitish: ${{ env.CLEAN_REF }}
          files: elementor-*.zip
          body: "Automated release for ${{ env.PACKAGE_VERSION }}"
          prerelease: ${{ env.PRERELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}
