name: One Click Release

on:
  workflow_dispatch:
    inputs:
      channel:
        required: true
        type: choice
        description: Select a channel. For cloud, use main branch only!
        options:
          - ga
          - beta
          - cloud
      pre_release:
        type: boolean
        description: 'Pre-release?'
        required: false

env:
  CHANNEL: ${{inputs.channel}}
  CHANGELOG_FILE: "temp-changelog.txt"

permissions:
  contents: write
  id-token: "write"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{inputs.branch}}


      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Env Vars Configure
        id: env_vars_configure
        uses: ./.github/workflows/env-vars-configure
        with:
          CHANNEL: ${{ env.CHANNEL }}
          REF: ${{ github.ref }}
          POSTFIX: ''

      - name: Update Readme.txt
        if: env.CHANNEL != 'cloud'
        uses: ./.github/workflows/update-readme-txt
        with:
          README_TXT_PATH: $GITHUB_WORKSPACE/readme.txt
          CHANNEL: ${{ env.CHANNEL }}
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      - name: Install Dependencies
        uses: ./.github/workflows/install-dependencies
      - name: Build plugin
        uses: ./.github/workflows/build-plugin
        with:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          BUILD_SCRIPT_PATH: "./.github/scripts/build-zip.sh"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          target_commitish: ${{ env.CLEAN_REF }}
          files: elementor-*.zip
          prerelease: ${{ github.event.inputs.pre_release }}
          body_path: ${{ env.CHANGELOG_FILE }}
